version: '3'
services:

  web:
    image: nginx:1.16.1
    mac_address: 02:00:00:fc:c8:1e
    expose: 
      - 443
      - 80
    networks:
      macvlan_bridge:
        #priority: 100
        ipv4_address: 158.69.107.120
      botsnet:
    volumes:
      # - "/home/docker/volumes/tauwebhooks/nginx-root:/usr/share/nginx/html:ro"
      - "/home/docker/volumes/bots/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/home/docker/volumes/bots/certs:/etc/letsencrypt/live/reg.vmo.mx"
      # port forwarding not needed
  tb: # tauros bots
    image: "taurosbot/tb"
    restart: on-failure
    command: "/bots/credentials-staging.json"
    ports: 
      - 9090:9090
    depends_on:
      - ox
      - gdax
    volumes:
      - ./bots:/bots
    networks:
      - botsnet
    stop_signal: SIGTERM
  ox: # openexchangerate grpc service
    image: "taurosbot/ox" 
    restart: on-failure
    volumes:
      - ./bots:/bots
    command: "/bots/credentials-staging.json"
    networks:
      - botsnet
  gdax: # gdax grpc service
    image: "taurosbot/gdax"
    restart: on-failure
    networks:
      - botsnet

networks:
  macvlan_bridge:
    external:
      name: vimo_macvlan_bridge
  botsnet:

# relay login -k 1ce835a0-7ddb-4c33-b10c-394f90ac78fa -s Hjja5aYuvumn