// Code generated by protoc-gen-go. DO NOT EDIT.
// source: balance.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
// = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BalancesRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=Market,proto3" json:"Market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalancesRequest) Reset()         { *m = BalancesRequest{} }
func (m *BalancesRequest) String() string { return proto.CompactTextString(m) }
func (*BalancesRequest) ProtoMessage()    {}
func (*BalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{0}
}

func (m *BalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalancesRequest.Unmarshal(m, b)
}
func (m *BalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalancesRequest.Marshal(b, m, deterministic)
}
func (m *BalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalancesRequest.Merge(m, src)
}
func (m *BalancesRequest) XXX_Size() int {
	return xxx_messageInfo_BalancesRequest.Size(m)
}
func (m *BalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalancesRequest proto.InternalMessageInfo

func (m *BalancesRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type Balance struct {
	Currency             string   `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Available            string   `protobuf:"bytes,2,opt,name=Available,proto3" json:"Available,omitempty"`
	Frozen               string   `protobuf:"bytes,3,opt,name=Frozen,proto3" json:"Frozen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{1}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Balance) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *Balance) GetFrozen() string {
	if m != nil {
		return m.Frozen
	}
	return ""
}

type Balances struct {
	Right                *Balance `protobuf:"bytes,1,opt,name=Right,proto3" json:"Right,omitempty"`
	Left                 *Balance `protobuf:"bytes,2,opt,name=Left,proto3" json:"Left,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balances) Reset()         { *m = Balances{} }
func (m *Balances) String() string { return proto.CompactTextString(m) }
func (*Balances) ProtoMessage()    {}
func (*Balances) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{2}
}

func (m *Balances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balances.Unmarshal(m, b)
}
func (m *Balances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balances.Marshal(b, m, deterministic)
}
func (m *Balances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balances.Merge(m, src)
}
func (m *Balances) XXX_Size() int {
	return xxx_messageInfo_Balances.Size(m)
}
func (m *Balances) XXX_DiscardUnknown() {
	xxx_messageInfo_Balances.DiscardUnknown(m)
}

var xxx_messageInfo_Balances proto.InternalMessageInfo

func (m *Balances) GetRight() *Balance {
	if m != nil {
		return m.Right
	}
	return nil
}

func (m *Balances) GetLeft() *Balance {
	if m != nil {
		return m.Left
	}
	return nil
}

func init() {
	proto.RegisterType((*BalancesRequest)(nil), "pb.BalancesRequest")
	proto.RegisterType((*Balance)(nil), "pb.Balance")
	proto.RegisterType((*Balances)(nil), "pb.Balances")
}

func init() { proto.RegisterFile("balance.proto", fileDescriptor_ee25a00b628521b1) }

var fileDescriptor_ee25a00b628521b1 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0xcc, 0x49,
	0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe4,
	0xe2, 0x77, 0x82, 0x08, 0x16, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x71, 0xb1,
	0xf9, 0x26, 0x16, 0x65, 0xa7, 0x96, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x4a,
	0xd1, 0x5c, 0xec, 0x50, 0xa5, 0x42, 0x52, 0x5c, 0x1c, 0xce, 0xa5, 0x45, 0x45, 0xa9, 0x79, 0xc9,
	0x95, 0x50, 0x45, 0x70, 0xbe, 0x90, 0x0c, 0x17, 0xa7, 0x63, 0x59, 0x62, 0x66, 0x4e, 0x62, 0x52,
	0x4e, 0xaa, 0x04, 0x13, 0x58, 0x12, 0x21, 0x00, 0x32, 0xdc, 0xad, 0x28, 0xbf, 0x2a, 0x35, 0x4f,
	0x82, 0x19, 0x62, 0x38, 0x84, 0xa7, 0xe4, 0xc7, 0xc5, 0x01, 0x73, 0x87, 0x90, 0x22, 0x17, 0x6b,
	0x50, 0x66, 0x7a, 0x06, 0xc4, 0x7e, 0x6e, 0x23, 0x6e, 0xbd, 0x82, 0x24, 0x3d, 0xa8, 0x64, 0x10,
	0x44, 0x46, 0x48, 0x9e, 0x8b, 0xc5, 0x27, 0x35, 0xad, 0x04, 0x6c, 0x3e, 0x9a, 0x0a, 0xb0, 0x84,
	0x91, 0x2b, 0xc2, 0x5f, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x46, 0x5c, 0xdc, 0xee,
	0xa9, 0x25, 0x70, 0x5b, 0x84, 0x91, 0x34, 0xc1, 0xfc, 0x2e, 0xc5, 0x83, 0x2c, 0xa8, 0xc4, 0x90,
	0xc4, 0x06, 0x0e, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0xeb, 0xbb, 0xfd, 0x3a,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// = grpc.SupportPackageIsVersion4

// BalancesServiceClient is the client API for BalancesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalancesServiceClient interface {
	GetBalances(ctx context.Context, in *BalancesRequest, opts ...grpc.CallOption) (*Balances, error)
}

type balancesServiceClient struct {
	cc *grpc.ClientConn
}

func NewBalancesServiceClient(cc *grpc.ClientConn) BalancesServiceClient {
	return &balancesServiceClient{cc}
}

func (c *balancesServiceClient) GetBalances(ctx context.Context, in *BalancesRequest, opts ...grpc.CallOption) (*Balances, error) {
	out := new(Balances)
	err := c.cc.Invoke(ctx, "/pb.BalancesService/GetBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalancesServiceServer is the server API for BalancesService service.
type BalancesServiceServer interface {
	GetBalances(context.Context, *BalancesRequest) (*Balances, error)
}

// UnimplementedBalancesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBalancesServiceServer struct {
}

func (*UnimplementedBalancesServiceServer) GetBalances(ctx context.Context, req *BalancesRequest) (*Balances, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalances not implemented")
}

func RegisterBalancesServiceServer(s *grpc.Server, srv BalancesServiceServer) {
	s.RegisterService(&_BalancesService_serviceDesc, srv)
}

func _BalancesService_GetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalancesServiceServer).GetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BalancesService/GetBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalancesServiceServer).GetBalances(ctx, req.(*BalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BalancesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BalancesService",
	HandlerType: (*BalancesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalances",
			Handler:    _BalancesService_GetBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balance.proto",
}
