# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='balance.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rbalance.proto\x12\x02pb\"!\n\x0f\x42\x61lancesRequest\x12\x0e\n\x06Market\x18\x01 \x01(\t\">\n\x07\x42\x61lance\x12\x10\n\x08\x43urrency\x18\x01 \x01(\t\x12\x11\n\tAvailable\x18\x02 \x01(\t\x12\x0e\n\x06\x46rozen\x18\x03 \x01(\t\"A\n\x08\x42\x61lances\x12\x1a\n\x05Right\x18\x01 \x01(\x0b\x32\x0b.pb.Balance\x12\x19\n\x04Left\x18\x02 \x01(\x0b\x32\x0b.pb.Balance2E\n\x0f\x42\x61lancesService\x12\x32\n\x0bGetBalances\x12\x13.pb.BalancesRequest\x1a\x0c.pb.Balances\"\x00\x62\x06proto3')
)




_BALANCESREQUEST = _descriptor.Descriptor(
  name='BalancesRequest',
  full_name='pb.BalancesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Market', full_name='pb.BalancesRequest.Market', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=54,
)


_BALANCE = _descriptor.Descriptor(
  name='Balance',
  full_name='pb.Balance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Currency', full_name='pb.Balance.Currency', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Available', full_name='pb.Balance.Available', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Frozen', full_name='pb.Balance.Frozen', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=118,
)


_BALANCES = _descriptor.Descriptor(
  name='Balances',
  full_name='pb.Balances',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Right', full_name='pb.Balances.Right', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Left', full_name='pb.Balances.Left', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=185,
)

_BALANCES.fields_by_name['Right'].message_type = _BALANCE
_BALANCES.fields_by_name['Left'].message_type = _BALANCE
DESCRIPTOR.message_types_by_name['BalancesRequest'] = _BALANCESREQUEST
DESCRIPTOR.message_types_by_name['Balance'] = _BALANCE
DESCRIPTOR.message_types_by_name['Balances'] = _BALANCES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BalancesRequest = _reflection.GeneratedProtocolMessageType('BalancesRequest', (_message.Message,), {
  'DESCRIPTOR' : _BALANCESREQUEST,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:pb.BalancesRequest)
  })
_sym_db.RegisterMessage(BalancesRequest)

Balance = _reflection.GeneratedProtocolMessageType('Balance', (_message.Message,), {
  'DESCRIPTOR' : _BALANCE,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:pb.Balance)
  })
_sym_db.RegisterMessage(Balance)

Balances = _reflection.GeneratedProtocolMessageType('Balances', (_message.Message,), {
  'DESCRIPTOR' : _BALANCES,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:pb.Balances)
  })
_sym_db.RegisterMessage(Balances)



_BALANCESSERVICE = _descriptor.ServiceDescriptor(
  name='BalancesService',
  full_name='pb.BalancesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=187,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBalances',
    full_name='pb.BalancesService.GetBalances',
    index=0,
    containing_service=None,
    input_type=_BALANCESREQUEST,
    output_type=_BALANCES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BALANCESSERVICE)

DESCRIPTOR.services_by_name['BalancesService'] = _BALANCESSERVICE

# @@protoc_insertion_point(module_scope)
